base_url = "https://korczis.github.io/psychonautic"
title = "Psychonautics"
description = "Komplexní česká encyklopedie psychoaktivních látek"
compile_sass = false
build_search_index = true
default_language = "en"
theme = "psychonautic"

[extra]
logo = "/logo.svg"
favicon = "/favicon.ico"

[search]
include_title = true
include_description = true
include_content = true

[[taxonomies]]
name = "tags"

[[taxonomies]]
name = "categories"

[[taxonomies]]
name = "kategorie"

[[taxonomies]]
name = "systemy"

[[taxonomies]]
name = "souvisejici_latky"
