base_url = "https://korczis.github.io/psychonautic"
title = "Psychonautics"
description = "Komplexní česká encyklopedie psychoaktivních látek"
compile_sass = false
build_search_index = true
default_language = "en"
theme = "psychonautic"

[extra]
logo = "/logo.svg"
favicon = "/favicon.ico"

# OG/Social meta defaults
og_image = "/images/og-default.png"
og_image_width = "1200"
og_image_height = "630"
twitter_site = "@psychonautics_cz"
twitter_creator = "@psychonautics_cz"
author = "Psychonautics"

[search]
include_title = true
include_description = true
include_content = true

[[taxonomies]]
name = "tags"

[[taxonomies]]
name = "categories"

[[taxonomies]]
name = "kategorie"

[[taxonomies]]
name = "systemy"

[[taxonomies]]
name = "souvisejici_latky"

[[taxonomies]]
name = "tridy"

[[taxonomies]]
name = "receptory"

[[taxonomies]]
name = "zdroje"

[[taxonomies]]
name = "aktivni_latky"

[[taxonomies]]
name = "keywords"

[[taxonomies]]
name = "authors"
